# Generated by Django 5.2.6 on 2025-11-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="email",
        ),
        migrations.RemoveField(
            model_name="record",
            name="phone",
        ),
    ]
