# Generated by Django 5.2.6 on 2025-11-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_record_email_remove_record_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="email",
            field=models.EmailField(default="andrewscrm@gmail.com", max_length=50),
        ),
        migrations.AddField(
            model_name="record",
            name="phone",
            field=models.CharField(default="+256 7*********", max_length=50),
        ),
    ]
